import React, { useState } from "react";
import CategoryFilter from "./CategoryFilter";
import TaskList from "./TaskList";
import NewTaskForm from "./NewTaskForm";
import { CATEGORIES, TASKS } from "../data";
import { v4 as uuidv4 } from 'uuid'; // Import uuidv4

function App() {

  const CATEGORIES = ["Code", "Food", "Money", "Misc"];
  // Map through the existing tasks and assign a unique ID to each task
  const initialTasks = TASKS.map(task => ({ ...task, id: uuidv4() }));
console.log(initialTasks)
  const [tasks, setTasks] = useState(initialTasks);
  const [selectedCategory, setSelectedCategory] = useState(null);

  const onCategoryChange = (category) => {
    setSelectedCategory(category === selectedCategory ? null : category);
  };

  const handleSubmit = (task) => {
    // Add the new task to the tasks array with a unique ID generated by uuidv4
    const newTask = { ...task, id: uuidv4() }; // Assign a unique ID
    setTasks([...tasks, newTask]);
  };

  const handleDelete = (taskId) => {
    // Filter out the task with the provided ID
    const updatedTasks = tasks.filter(task => task.id !== taskId);
    // Update the tasks state with the filtered tasks
    setTasks(updatedTasks);
  };

  return (
    <div className="App">
      <h2>My tasks</h2>
      <CategoryFilter CATEGORIES={CATEGORIES} onCategoryChange={onCategoryChange} />
      <NewTaskForm onTaskFormSubmit={handleSubmit} CATEGORIES={CATEGORIES} />
      <TaskList tasks={tasks} onDeleteTask={handleDelete} selectedCategory={selectedCategory} />
    </div>
  );
}

export default App;